### ISSUE TITLE
Hello, at some point the bot just gets up. an error is written on the game screen and the bot does not see this to restart the script.

### ISSUE THREAD

**Issue by nailnn** [brunochicoria/BombCrypto-Bot#1]
Hello, at some point the bot just gets up. an error is written on the game screen and the bot does not see this to restart the script.

`Press 1 to start!
Clicking on connect
Clicking on metamask
Clicking on sign
Loggin in!
Searching for targets/treasure-hunt-icon.png
Found it!
Clicking on heroes
Putting heroes to work!
Searching for targets/treasure-hunt-icon.png
Found it!
This is where fun begins!!!
Searching for targets/ok.png
No ok button
Searching for targets/ok.png
No ok button
Searching for targets/ok.png
Traceback (most recent call last):
  File "C:\Users\DR\Desktop\BombCryptoBot\bombCryptoBot.py", line 173, in <module>
    main()
  File "C:\Users\DR\Desktop\BombCryptoBot\bombCryptoBot.py", line 170, in main
    main1()
  File "C:\Users\DR\Desktop\BombCryptoBot\bombCryptoBot.py", line 146, in main1
    loop()
  File "C:\Users\DR\Desktop\BombCryptoBot\bombCryptoBot.py", line 113, in loop
    checkOkBtn()
  File "C:\Users\DR\Desktop\BombCryptoBot\bombCryptoBot.py", line 82, in checkOkBtn
    locateImageClick(ok_icon, 30)
  File "C:\Users\DR\Desktop\BombCryptoBot\bombCryptoBot.py", line 55, in locateImageClick
    image_search = pyautogui.locateOnScreen(image,grayscale=True, confidence=0.5)
  File "C:\Users\DR\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyautogui\__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "C:\Users\DR\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyautogui\__init__.py", line 213, in locateOnScreen
    return pyscreeze.locateOnScreen(*args, **kwargs)
  File "C:\Users\DR\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyscreeze\__init__.py", line 372, in locateOnScreen
    screenshotIm = screenshot(region=None) # the locateAll() function must handle cropping to return accurate coordinates, so don't pass a region here.
  File "C:\Users\DR\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyscreeze\__init__.py", line 145, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "C:\Users\DR\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyscreeze\__init__.py", line 457, in _screenshot_win32
    im = ImageGrab.grab()
  File "C:\Users\DR\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PIL\ImageGrab.py", line 43, in grab
    offset, size, data = Image.core.grabscreen_win32(
OSError: screen grab failed

C:\Users\DR\Desktop\BombCryptoBot>python bombCryptoBot.py
If are enjoying the bot you can send me Bcoins :)
Wallet: 0xb623CdA9c073220B8D7C9742A08cB576AD9aB392
Press 1 to start!
Clicking on connect
Clicking on metamask
Clicking on sign
Loggin in!
Searching for targets/treasure-hunt-icon.png
Found it!
Clicking on heroes
Putting heroes to work!
Searching for targets/treasure-hunt-icon.png
Found it!
This is where fun begins!!!
Searching for targets/ok.png
Traceback (most recent call last):
  File "C:\Users\DR\Desktop\BombCryptoBot\bombCryptoBot.py", line 173, in <module>
    main()
  File "C:\Users\DR\Desktop\BombCryptoBot\bombCryptoBot.py", line 170, in main
    main1()
  File "C:\Users\DR\Desktop\BombCryptoBot\bombCryptoBot.py", line 146, in main1
    loop()
  File "C:\Users\DR\Desktop\BombCryptoBot\bombCryptoBot.py", line 113, in loop
    checkOkBtn()
  File "C:\Users\DR\Desktop\BombCryptoBot\bombCryptoBot.py", line 83, in checkOkBtn
    moveAndClick(pos10)
  File "C:\Users\DR\Desktop\BombCryptoBot\bombCryptoBot.py", line 34, in moveAndClick
    pyautogui.moveTo(pos[0],pos[1])
  File "C:\Users\DR\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyautogui\__init__.py", line 597, in wrapper
    failSafeCheck()
  File "C:\Users\DR\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyautogui\__init__.py", line 1722, in failSafeCheck
    raise FailSafeException(
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.

C:\Users\DR\Desktop\BombCryptoBot>`

@nailgvozdev

**Comment by nailnn** [comment]
![2021-11-18_02-41-01](https://user-images.githubusercontent.com/76922428/142299857-c9f90cdb-2433-46e1-b27e-526b39050d0e.png)

**Comment by brunochicoria** [comment]
Hi, try to add this after the imports
pyautogui.FAILSAFE = False
